version: 2.1
orbs:
  docker: circleci/docker@0.5.19
workflows:
  version: 2
  build-and-publish:
    jobs:
      - docker/publish:
          cache_from: "pennlabs/tox:latest"
          image: pennlabs/tox
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          filters:
            branches:
              only:
                - master
